# -*- coding: utf-8 -*-
"""ScriptPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vJnsVi2uKPc_rmiEKhp5mzg1gBirMNp
"""

import cv2
import numpy as np
from ultralytics import YOLO
import matplotlib.pyplot as plt
import os

# -------------------------------------------------------------
#  CARGAR EL MODELO YOLO (CAMBIA ESTA RUTA POR TU MODELO LOCAL)
# -------------------------------------------------------------
# Ejemplo:
# model = YOLO("best_plate_yolo11m.pt")
model = YOLO("/content/best_plate_yolo11m .pt")   # <-- EDITA ESTO


# -------------------------------------------------------------
# FUNCIÓN PARA DETECTAR Y DIBUJAR LA PLACA EN UNA SOLA IMAGEN
# -------------------------------------------------------------
def detectar_placa(img_path):
    # Leer imagen
    img = cv2.imread(img_path)
    if img is None:
        print(f"❌ No se pudo cargar la imagen: {img_path}")
        return None

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Inferencia
    results = model(img_rgb, verbose=False)
    boxes = results[0].boxes.xyxy.cpu().numpy()

    if len(boxes) == 0:
        print("❌ No se detectó ninguna placa.")
        return img_rgb

    # Tomar primera detección
    x1, y1, x2, y2 = map(int, boxes[0])

    # Dibujar recuadro
    cv2.rectangle(img_rgb, (x1, y1), (x2, y2), (0, 255, 0), 3)

    return img_rgb


# -------------------------------------------------------------
# PROCESAR UNA SOLA IMAGEN
# -------------------------------------------------------------
def procesar_imagen_unica(ruta_imagen):
    resultado = detectar_placa(ruta_imagen)

    if resultado is None:
        return

    plt.figure(figsize=(12, 8))
    plt.imshow(resultado)
    plt.axis("off")
    plt.title("Placa detectada")
    plt.show()

    # Guardar salida
    nombre_salida = "resultado_placa.png"
    plt.imsave(nombre_salida, resultado)
    print(f"✅ Imagen guardada como: {nombre_salida}")


# -------------------------------------------------------------
# EJECUCIÓN
# -------------------------------------------------------------
if __name__ == "__main__":
    # Cambia aquí la ruta de la imagen que deseas probar
    ruta = "/content/images.jpg"   # <-- EDITA ESTO

    procesar_imagen_unica(ruta)